// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3qaaxs1lRkl1dqUnS6RNUFn9JI2Rw6xE',
    appId: '1:151841537348:web:0c883c2e57fc2d54bc6b11',
    messagingSenderId: '151841537348',
    projectId: 'travel-app-50412',
    authDomain: 'travel-app-50412.firebaseapp.com',
    storageBucket: 'travel-app-50412.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4RAM6MEGnPs8wKdx7shSJkv1WfMYlyGY',
    appId: '1:151841537348:android:64469815f0ffbadebc6b11',
    messagingSenderId: '151841537348',
    projectId: 'travel-app-50412',
    storageBucket: 'travel-app-50412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYvw5AET7ioVi1frTXHPdGgIfSEyPC6Yc',
    appId: '1:151841537348:ios:93a0f9e94af57083bc6b11',
    messagingSenderId: '151841537348',
    projectId: 'travel-app-50412',
    storageBucket: 'travel-app-50412.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYvw5AET7ioVi1frTXHPdGgIfSEyPC6Yc',
    appId: '1:151841537348:ios:93a0f9e94af57083bc6b11',
    messagingSenderId: '151841537348',
    projectId: 'travel-app-50412',
    storageBucket: 'travel-app-50412.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3qaaxs1lRkl1dqUnS6RNUFn9JI2Rw6xE',
    appId: '1:151841537348:web:8ef31d893c58a757bc6b11',
    messagingSenderId: '151841537348',
    projectId: 'travel-app-50412',
    authDomain: 'travel-app-50412.firebaseapp.com',
    storageBucket: 'travel-app-50412.firebasestorage.app',
  );
}
